### ISSUE TITLE
error send media

### ISSUE THREAD

**Issue by renzhaxor** [ariffb25/stikerinbot#141]
ERROR [2021-09-21 19:51:31.509 +0000] (21319): Error in uploading to med
ia.fblr22-1.fna.whatsapp.net, retrying...
    class: "Baileys"
ERROR [2021-09-21 19:51:32.385 +0000] (21319): Error in uploading to med
ia-xsp1-3.cdn.whatsapp.net, retrying...
    class: "Baileys"
ERROR [2021-09-21 19:51:32.841 +0000] (21319): Error in uploading to mmg
.whatsapp.net
    class: "Baileys"
Error: Media upload failed on all hosts
    at WAConnection.prepareMessageMedia (/skuy/lib/simple.js:379:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5
)
    at async WAConnection.prepareMessageContent (/skuy/node_modules/@adi
wajshing/baileys/lib/WAConnection/6.MessagesSend.js:128:21)
    at async WAConnection.prepareMessage (/skuy/node_modules/@adiwajshin
g/baileys/lib/WAConnection/6.MessagesSend.js:54:25)
    at async WAConnection.sendMessage (/skuy/node_modules/@adiwajshing/b
aileys/lib/WAConnection/6.MessagesSend.js:24:27)
    at async WAConnection.sendFile (/skuy/lib/simple.js:661:14) unhandle
dRejection
 >

**Comment by ariffb25** [comment]
https://github.com/adiwajshing/Baileys/issues/513
