### ISSUE TITLE
Tebak gambar error

### ISSUE THREAD

**Issue by iniariaaa** [ariffb25/stikerinbot#61]
TypeError: Cannot read property 'toString' of undefined
    at Object.getStream (c:\botwea\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:330:18)
    at Object.encryptedStream (c:\botwea\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:379:44)
    at WAConnection.prepareMessageMedia (c:\botwea\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:169:124)
    at WAConnection.prepareMessageContent (c:\botwea\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:128:32)
    at WAConnection.prepareMessage (c:\botwea\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:54:36)
    at WAConnection.sendButtonImg (c:\botwea\lib\simple.js:264:28)
    at WAConnection.handler (c:\botwea\plugins\tebakgambar.js:36:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WAConnection.handler (c:\botwea\handler.js:451:13)

**Comment by OPPAI-HUNTER** [comment]
ntah

**Comment by ariffb25** [comment]
fix
