### ISSUE TITLE
ERROR Identifier 'jadibot' has already been declared 

### ISSUE THREAD

**Issue by MrMeegoy** [ariffb25/stikerinbot#7]
ketika menjalankan bot ini muncul error pada console, apakah ini berpengaruh ke bot nya ketika di jalankan?

let jadibot = [...new Set([...global.conns.filter(conn => conn.user && conn.state !== 'close').map(conn => conn.user)])]
            ^

    SyntaxError: Identifier 'jadibot' has already been declared
        at wrapSafe (internal/modules/cjs/loader.js:1001:16)
        at Module._compile (internal/modules/cjs/loader.js:1049:27)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
        at Module.load (internal/modules/cjs/loader.js:950:32)
        at Function.Module._load (internal/modules/cjs/loader.js:790:14)
        at Module.require (internal/modules/cjs/loader.js:974:19)
        at require (internal/modules/cjs/helpers.js:92:18)
        at Object.<anonymous> (C:\Users\meegoy\Desktop\stikerinbot\main.js:165:32)
        at Module._compile (internal/modules/cjs/loader.js:1085:14)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

**Comment by ariffb25** [comment]
done
